### PR TITLE
Use HTTPoison :recv_timeout option

### PR DESCRIPTION
**Pull request by davidefedrigo**
See https://github.com/SparkPost/elixir-sparkpost/issues/25.

Test coverage is still 100%.

### CODE REVIEW

**Comment by davidefedrigo** [comment]
Hi there, anyone? Am I the only one with this problem?

**Comment by ewandennis** [comment]
Hi there @davidefedrigo - deepest thanks for the contribution and sorry I missed this. IMO your PR is useful even if you're the only one with the issue.

It took me a moment to grok the definition of `:recv_timeout` - it's the timeout waiting for `recv()` I guess rather than the "timeout used with receiving a connection" as [noted here](https://hexdocs.pm/httpoison/HTTPoison.html#options/3).

Anyway, lets get it merged.

**Comment by ewandennis** [comment]
@davidefedrigo Looking again at this, you have changed the meaning of `:timeout` from "connection timeout" to "recv timeout". To avoid the breaking change, I'm think I'm going to make your socket `recv()` timeout into an `:http_recv_timeout` and leave the original semantics in place. I hope that small change won't have too large an impact on your own code.

**Comment by davidefedrigo** [comment]
Yes, I changed back that meaning on purpose because it was the original one, when HTTPotion was in use... if I didn't misunderstand it! :) When I upgraded to HTTPoison I started to get timeout errors, and that was the clue that led me to open the issue.

Anyway, your change it's pretty fine with me. Thanks for notifying me, I just need to update the config of a single project. ;)

Thank you again!

**Pull request merged**
