### PR TITLE
HTTPoison Conversion

### PR DESCRIPTION
**Pull request by DavidAntaramian**
* Switch to HTTPoison dependency
* Refactor tests to use HTTPoison

This addresses #12, which thankfully was very isolated. The largest factor of the changes was making sure callers of `SparkPost.Endpoint.request/3` were updated to call `SparkPost.Endpoint.request/5` correctly. `request/5` is modeled to be identical to the underlying `HTTPoison.request` that it calls.

The majority of the changes to tests were handled by updating the mocks, but as I mentioned in #13, I think these tests are very fragile since they are not testing the true functionality of the module. That being said, I've done some manual testing which works. :ok_hand:

I did make a small change to the config file layout which uses the typical tiered layout.

@ewandennis @richleland

### CODE REVIEW

**Comment by princemaple** [comment]
hello?

**Comment by ewandennis** [comment]
My my.  This PR has been open waaay too long for which I apologise.

@DavidAntaramian - would you mind bumping httpoison to v0.9.0 and we'll get this merged down?

I'd also love a chat about test strategy at some point.  I'll come find you on Slack...

**Comment by DavidAntaramian** [comment]
@ewandennis I should be able to find some time this week. Will do!

**Comment by princemaple** [comment]
@ewandennis could this be merged now?

**Pull request merged**
